#!/usr/bin/env bash
#This code prints a "Best School" 10 times and Hi at position 9
i=1
while [ "$i" -le 10 ]; do
    echo "Best School"
    if [ "$i" == 9 ]; then
        echo "Hi"
    fi
    i=$((i+1))
done
