#!/usr/bin/env bash
#Displaying the hors and minutes of a clock
Hour=0
while [ "$Hour" -le 12 ]; do
    echo "Hour: $Hour"
        mins=1
        while [ "$mins" -le 59 ]; do
            echo "$mins"
            mins=$((mins+1))
        done
    Hour=$((Hour+1))
done
 
      
